### PR TITLE
Changed how the panels in the SidePanel is saved, added scroll to SidePanel. 

### LINKED ISSUE #41: Add scroll to sidepanel
When you add too many shapes you can not see some of them as they are below the edge of the panel. Need to implement the possibility to scroll down. This is currently on the implement-panel branch

### PR DESCRIPTION
**Pull request by pontusluthi**
Redid how the wxPanel* is saved, now saved in the Shape object. Fixed #41 so sidepanel is now scrollable. Merged implement-panel into shape-has-wxpanel to fix merge conflicts locally.

### CODE REVIEW

**Review by aldenbro — CHANGES_REQUESTED** [review]
Testade shape-has-wxpanel och skroll vid overflow verkade inte fungera? Något jag missar?

**Review by alexKth — CHANGES_REQUESTED** [review]
Good additions! Some notes:

- We probably want the coordinates of the Point shape to display in the sidebar.
- The info boxes in the sidepanel do not disappear once the shape is removed.
- The info boxes in the sidepanel change order sometimes, not the most intuitive.
- Comments in the Shape::CreatePanel reference a "NULL parent" which has since been removed.
- It seems like SidePanel::Update creates new panels instead of using those inside of the shapes? This seems like something we do not want.

ta bort rutor när form tas bort
kommentarer om "parent window" i Shape::CreatePanel implementationerna är föråldrade
SidePanel::Update skapar nya paneler istället för att använda de som finns?

**Comment by pontusluthi** [comment]
Flesta problem borde vara lösta nu, testa gärna igen så att jag inte missade något

**Review by alexKth — APPROVED** [review]
LGTM!

**Pull request merged**
